### ISSUE TITLE
.boltrc config: don’t parse non-component packages

### ISSUE THREAD

**Issue by sghoweri** [boltdesignsystem/bolt#1274]
Right now adding NPM packages that aren’t Bolt components can result in a fatal Bolt build tool error getting thrown, as @christophersmith262 and @remydenton can attest to.

**Comment by remydenton** [comment]
As part of this, fix (or remove?) the incorrect path to the schema file in the build tools package.json:
https://github.com/bolt-design-system/bolt/blob/master/packages/build-tools/utils/package.json#L43

**Comment by christophersmith262** [comment]
Best fix from my perspective would be to have a way for a package (in package.json) to declare that it has a component in it. Or better yet, to have an entry in the schema that says "this is schema for twig, this is schema for a web component, this is schema for javascript config, etc.".

**Comment by remydenton** [comment]
I think we may have smushed two separate issues together in this one:
1. There's no easy way to tell whether a package is a component or something else by looking at its `package.json` file (our current workaround is to check whether the `name` starts with `@bolt/components`).  This is a use case for work @christophersmith262 is doing on the base theme.
2. You get this error if you list build utils in your boltrc file
```
node_modules/@bolt/build-utils/utils/config.schema.yml
Error: This file ^^^ does not exist and it was referenced in package.json for that component, please make sure the file path is correct.
```
This can be fixed by any of
  a) don't list build utils in boltrc (it's unnecessary)
  b) fix the path to the schema file in build tools package.json in Bolt
  c) "don't parse non-component packages".

Did I get that right?
