### ISSUE TITLE
`bolt-theme` uses final item in the map, irrespective of theme. 

### ISSUE THREAD

**Issue by glassdimly** [boltdesignsystem/bolt#1443]
As I understand it, the following should result in `yellow` background on `dark`/`xdark`, `white` on `light`/`xlight`:

`packages/micro-journeys/src/nav-shared.scss`
```
    background-color: bolt-theme(
      (
        // Should be yellow
        xdark: primary,
        dark: primary,
        // Should be white
        light: secondary,
        xlight: secondary,
      )
    );
```
Results in this:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/1361104/65338529-05c3c380-db90-11e9-849c-69f9e1329542.png">

This is present in Chrome and FF.

This can be seen here: https://boltdesignsystem-mar7a5s5m.now.sh/pattern-lab/?p=experiments-micro-journeys

**Comment by glassdimly** [comment]
Also, I spoke for a while with @mikemai2awesome about this issue.

**Comment by sghoweri** [comment]
@glassdimly looking into this — I'll keep you posted.

**Comment by sghoweri** [comment]
@WessWillis @glassdimly just a quick update on this one: 

From what I can tell, I think half the issue here likely has to do with the PostCSS plugin never supporting `bolt-theme` inside of media queries. 

I'm working on a fix for at least that piece however we'll still need to address how best to handle theming UI that's fully encapsulated in the Shadow DOM since the default `t-bolt-THEME` contextual selectors wouldn't apply in those situations.
