### ISSUE TITLE
A card with no image or video should omit the "c-bolt-card__media"

### ISSUE THREAD

**Issue by mikemai2awesome** [boltdesignsystem/bolt#311]
If no data is passed into a card for an image or a video, the card markup should not write out the `c-bolt-card__media` container.

Currently it is still spitting out the `c-bolt-card__media` container and also spits out the first item's data inside that container.

**Comment by remydenton** [comment]
Heavens, that `card.twig` template is complex; there's almost no code comments in the file to explain what's happening (not to mention no schema definition).

### Bug Replication
If I look at the [card-w-teaser](https://bolt.netlify.com/?p=components-card-w-teaser) example, I see there's a `c-bolt-link` element inside `c-bolt-card__media`.  Because it's not empty, the `c-bolt-card__media` prints.  **That's the issue you're referring to, right @mikemai2awesome **?

### Problem
The reason is that the loop inside `{% block card_media %}` will print out a link, even though link is not one of the things allowed in `_allowedCardHeaderItems`.  That is in turn because the following expression evaluates to true if the `key` is `0`, which is the case for link.  That's obviously not intended.

[`{% if item.pattern in _allowedCardHeaderItems or key in _allowedCardHeaderItems %}`](https://github.com/bolt-design-system/bolt/blob/release/0.x/src/_patterns/02-components/bolt-card/src/card.twig#L93)

### Solution
Under what circumstances is `key` numeric vs a string we should actually evaluate though?  It's very difficult to tell because of that lack of definition for what's being passed in to this pattern.  I think this file needs some better documentation of that before I should attempt a fix.  Maybe @sghoweri has ideas for a decent fix?

**Comment by sghoweri** [comment]
@remydenton I was talking to @mikemai2awesome about this - 100% percent agreed that the card.twig template is way way too complex.

What I was proposing to him was to simply cut out the magic here and to not have any restrictions on what content can be dropped into what sections, eliminating virtually all of the crazy logic we're having to introduce with this

**Comment by remydenton** [comment]
Cool, makes sense @sghoweri.  Basically, just treat it as a layout pattern and allow consumers to put anything in the various sections.  A couple considerations though:

- It looks like Drupal is passing `image`, `video`, `teaser`, and `url`, so we'd probably want backwards compatibility for those at least (perhaps deprecate some of them).
- In addition to layout, this pattern also determines how linking should work (i.e. should the media link?  yes if it's an image, no if a video...).  So, we'd probably want to keep just enough options for that to still work.

I may not get to this for some time since it's not a quick task and we've got plenty else on our plates at the moment-- but that is at least a good strategy!

**Comment by mikemai2awesome** [comment]
@EvanLovely @remydenton You can see the issue here. The cards on top, and the cards in the search listing. http://5a69f299efbe5d29bc58aca6.bolt.netlify.com/patterns/04-pages-d8-news-d8-media-browse--list-view/04-pages-d8-news-d8-media-browse--list-view.html
